### PR TITLE
Add test for Ember 3.1 ES5 getters

### PR DESCRIPTION
**Pull request by paulcwatts**
One potential addition would be to test the "else" case, where ES5 getters are not defined -- can we assert that the values would be different? I'm not sure.

### CODE REVIEW

**Comment by pzuraq** [comment]
> where ES5 getters are not defined

Unsure what you mean by this, do you mean `@computed foo` instead of `@computed get foo`? If so, that's no longer supported

**Comment by paulcwatts** [comment]
I mean add a case for Ember < 3.1. For Ember < 3.1, I have no idea if `this.fullName !== this.get('fullName')` or if that can be relied on.

**Comment by pzuraq** [comment]
ah, gotcha. I don't think we should test that, in the Ember < 3.1 case the behavior of `this.fullName` is just undefined, we don't provide any guarantees about it.

**Comment by pzuraq** [comment]
Thanks for getting this in, really appreciate it!

**Pull request merged**
